import { useState, useMemo, useEffect } from 'react'
import { useParams, useNavigate, Link } from 'react-router-dom'
import { motion, AnimatePresence } from 'framer-motion'
import {
  ArrowLeft,
  Heart,
  User,
  Calendar,
  Phone,
  FileText,
  ClipboardList,
  Clock,
  Pill,
  FlaskConical,
  AlertTriangle,
  Users,
  Cigarette,
  Wine,
  Download,
  ExternalLink,
  Check,
  X,
  Activity,
  Eye,
  Sparkles,
  Code,
  Leaf,
  Shield,
  Brain,
  Edit3,
  Stethoscope,
  Plus,
  QrCode,
  ShieldCheck,
  CheckCircle2
} from 'lucide-react'
import Button from '../../components/Button'
import Card from '../../components/Card'
import Badge from '../../components/Badge'
import ConfidenceBadge from '../../components/ConfidenceBadge'
import ClinicalSignalCard from '../../components/ClinicalSignalCard'
import VerificationButtons from '../../components/VerificationButtons'
import Timeline from '../../components/Timeline'
import EvidenceDrawer from '../../components/EvidenceDrawer'
import DocumentInspectorModal from '../../components/DocumentInspectorModal'
import DrugSafetyBanner from '../../components/DrugSafetyBanner'
import DifferentialDiagnosisWidget from '../../components/DifferentialDiagnosisWidget'
import LLMSummaryGenerator from '../../components/LLMSummaryGenerator'
import { getPatientById, updateRegisteredPatientField } from '../../services/sessionStore'
import { prepareFHIRBundle } from '../../services/abdmService'
import { generateDifferentialDiagnosis } from '../../services/differentialEngine'
import { isDoctorAuthenticated } from '../../services/doctorAuthService'

const tabs = [
  { id: 'summary', label: 'Structured Summary & LLM', icon: ClipboardList },
  { id: 'problems', label: 'Problems & Symptoms', icon: Activity },
  { id: 'documents', label: 'Medical Reports & OCR', icon: FileText },
  { id: 'timeline', label: 'Chronological Timeline', icon: Clock },
  { id: 'ayush', label: 'Dashavidha Pariksha (AYUSH)', icon: Leaf },
]

export default function PatientDetail() {
  const { id } = useParams()
  const navigate = useNavigate()

  // Protect route
  useEffect(() => {
    if (!isDoctorAuthenticated()) {
      navigate('/doctor/login', { replace: true })
    }
  }, [navigate])

  const [activeTab, setActiveTab] = useState('summary')
  const [sectionStatuses, setSectionStatuses] = useState({})
  const [acceptedICD, setAcceptedICD] = useState(null)

  // Evidence Drawer & Document Inspector Modal states
  const [activeEvidence, setActiveEvidence] = useState(null)
  const [activeInspectorDoc, setActiveInspectorDoc] = useState(null)
  const [fhirModalOpen, setFhirModalOpen] = useState(false)

  const patient = useMemo(() => getPatientById(id), [id])
  const { summary = {}, clinicalSignals = [], timeline = [], documents = [], interviewResponses = [] } = patient

  // Editable Summary State for Doctor Corrections
  const [summaryData, setSummaryData] = useState(summary)
  useEffect(() => {
    setSummaryData(patient.summary || {})
  }, [patient])

  const [editModal, setEditModal] = useState({
    isOpen: false,
    sectionKey: '',
    title: '',
    textValue: ''
  })

  // Physician Clinical Notes & Orders State
  const [physicianOrders, setPhysicianOrders] = useState({
    diagnosis: '',
    clinicalNotes: '',
    medications: [
      { name: 'Tab Aspirin 75 mg', instructions: 'Once daily after breakfast', duration: '30 days' },
      { name: 'Tab Atorvastatin 20 mg', instructions: 'Once daily at bedtime', duration: '30 days' },
    ],
    labOrders: ['12-Lead ECG (STAT)', 'Serum Troponin-I', 'Lipid Profile', 'HbA1c'],
    isSigned: false,
    signedAt: null
  })

  // Differential Diagnosis generated by AI engine
  const differentials = useMemo(() => {
    return generateDifferentialDiagnosis(patient)
  }, [patient])

  // Handle Section Verification Status Toggle
  const handleSectionVerify = (sectionKey, newStatus) => {
    setSectionStatuses(prev => ({
      ...prev,
      [sectionKey]: newStatus,
    }))
  }

  // Handle Section Editing by Doctor
  const handleOpenEdit = (sectionKey, title, currentValue) => {
    let initialText = ''
    if (typeof currentValue === 'string') initialText = currentValue
    else if (Array.isArray(currentValue)) initialText = currentValue.join('\n')
    else if (typeof currentValue === 'object' && currentValue !== null) {
      initialText = Object.entries(currentValue).map(([k, v]) => `${k}: ${v}`).join('\n')
    }
    setEditModal({
      isOpen: true,
      sectionKey,
      title,
      textValue: initialText
    })
  }

  const handleSaveEdit = () => {
    setSummaryData(prev => ({
      ...prev,
      [editModal.sectionKey]: editModal.textValue
    }))
    setSectionStatuses(prev => ({
      ...prev,
      [editModal.sectionKey]: 'edited'
    }))
    setEditModal({ isOpen: false, sectionKey: '', title: '', textValue: '' })
  }

  // Sign & Complete Consultation
  const handleSignConsultation = () => {
    setPhysicianOrders(prev => ({
      ...prev,
      isSigned: true,
      signedAt: new Date().toISOString()
    }))

    if (patient.patientId || patient.id) {
      updateRegisteredPatientField(patient.patientId || patient.id, {
        consultationStatus: 'completed',
        completedAt: new Date().toISOString()
      })
    }
  }

  const isCompleted = physicianOrders.isSigned || patient.consultationStatus === 'completed'

  return (
    <div className="min-h-screen bg-[#f7f9fb] text-slate-900 flex flex-col select-none pb-20 w-full max-w-full overflow-x-hidden">
      {/* Top Navigation Bar */}
      <header className="sticky top-0 z-30 bg-white/95 backdrop-blur-md border-b border-slate-200/80 px-4 sm:px-6 py-3 shadow-xs w-full max-w-full overflow-x-hidden">
        <div className="max-w-7xl mx-auto flex items-center justify-between gap-3">
          <div className="flex items-center gap-3 min-w-0">
            <Link
              to="/doctor"
              className="p-2 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 transition cursor-pointer"
              title="Back to Patient Queue"
            >
              <ArrowLeft className="size-4" />
            </Link>
            <div className="min-w-0">
              <div className="flex items-center gap-2">
                <span className="w-8 h-8 rounded-xl bg-teal-50 text-teal-800 font-mono font-bold text-xs flex items-center justify-center border border-teal-200">
                  {patient.queueToken || '#A-14'}
                </span>
                <h1 className="font-heading font-bold text-base sm:text-lg text-slate-900 truncate">
                  {patient.name}
                </h1>
                <span className="text-xs text-slate-500 font-medium">
                  {patient.age ? `${patient.age}y` : ''} • {patient.gender || 'Patient'}
                </span>
              </div>
            </div>
          </div>

          <div className="flex items-center gap-2 shrink-0">
            {isCompleted && (
              <span className="px-3 py-1 rounded-full bg-emerald-100 text-emerald-800 text-xs font-bold flex items-center gap-1">
                <CheckCircle2 className="size-3.5" /> Signed & Completed
              </span>
            )}
            <button
              type="button"
              onClick={() => setFhirModalOpen(true)}
              className="px-3 py-1.5 rounded-xl bg-teal-50 hover:bg-teal-100 text-teal-800 border border-teal-300 text-xs font-bold transition flex items-center gap-1.5 cursor-pointer shadow-2xs"
            >
              <QrCode className="size-3.5" />
              <span>FHIR / ABDM Bundle</span>
            </button>
          </div>
        </div>
      </header>

      {/* Main Container */}
      <main className="flex-1 max-w-7xl mx-auto w-full px-4 sm:px-6 py-6 space-y-6 overflow-x-hidden">
        {/* Patient Profile & Critical Safety Banners */}
        <div className="p-5 rounded-3xl bg-white border border-slate-200 shadow-xs space-y-4">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
            <div className="flex items-center gap-4">
              <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-teal-600 to-teal-700 text-white font-heading font-bold text-xl flex items-center justify-center shadow-md">
                {(patient.name || 'P')[0]}
              </div>
              <div>
                <div className="flex items-center gap-2 flex-wrap">
                  <h2 className="font-heading font-bold text-lg text-slate-900">{patient.name}</h2>
                  <span className="font-mono text-xs font-bold text-teal-800 bg-teal-50 px-2.5 py-0.5 rounded-full border border-teal-200">
                    ABHA: {patient.abhaId || '91-8842-1920-4491'}
                  </span>
                  <span className="font-mono text-xs font-bold text-slate-600 bg-slate-100 px-2.5 py-0.5 rounded-full">
                    Phone: {patient.phone || '+91 98765 43210'}
                  </span>
                </div>
                <p className="text-xs text-slate-600 mt-1 font-semibold">
                  Chief Complaint:{' '}
                  <span className="text-teal-800 font-bold">{patient.chiefComplaint || 'Chest pain for 3 days'}</span>
                </p>
              </div>
            </div>

            <div className="flex items-center gap-2 self-end sm:self-auto">
              <span className="px-3 py-1 rounded-xl bg-amber-50 border border-amber-200 text-amber-800 font-mono text-xs font-bold">
                ESI Level 3 (Urgent)
              </span>
            </div>
          </div>

          {/* Real-time Drug & Allergy Safety Contraindication Alert */}
          <DrugSafetyBanner
            medications={summaryData.medications || patient.currentMedications || ['Metformin 500mg']}
            allergies={patient.knownAllergies || ['Penicillin']}
            isCardiacHistory={patient.isCardiacHistory ?? true}
          />
        </div>

        {/* Clinical Tabs Navigation */}
        <div className="flex items-center gap-1.5 overflow-x-auto no-scrollbar overscroll-contain touch-pan-x border-b border-slate-200 pb-2 w-full max-w-full">
          {tabs.map((tab) => {
            const Icon = tab.icon
            const isActive = activeTab === tab.id
            return (
              <button
                key={tab.id}
                type="button"
                onClick={() => setActiveTab(tab.id)}
                className={`px-4 py-2 rounded-2xl text-xs font-bold transition flex items-center gap-2 cursor-pointer whitespace-nowrap ${
                  isActive
                    ? 'bg-teal-700 text-white shadow-xs'
                    : 'bg-white hover:bg-slate-100 text-slate-700 border border-slate-200/80'
                }`}
              >
                <Icon className="size-4" />
                <span>{tab.label}</span>
              </button>
            )
          })}
        </div>

        {/* TAB 1: STRUCTURED SUMMARY & INTEGRATED LLM GENERATOR */}
        {activeTab === 'summary' && (
          <div className="space-y-6">
            {/* Integrated Clinical LLM Summary Generator */}
            <LLMSummaryGenerator
              patient={patient}
              responses={interviewResponses}
              documents={documents}
              defaultLang="en"
              autoGenerate={true}
              collapsible={false}
              mode="doctor"
            />

            {/* Differential Diagnoses (ICD-10 Ranking) */}
            <DifferentialDiagnosisWidget
              differentials={differentials}
              acceptedCode={acceptedICD}
              onAcceptICD={(code) => {
                setAcceptedICD(code)
                setPhysicianOrders(prev => ({ ...prev, diagnosis: code }))
              }}
            />

            {/* 8-Part Structured Clinical Intake Summary with Verification Controls */}
            <div className="p-5 rounded-3xl bg-white border border-slate-200 shadow-xs space-y-5">
              <div className="flex items-center justify-between border-b border-slate-100 pb-3">
                <div>
                  <h3 className="font-heading font-bold text-base text-slate-900">
                    8-Part Structured Clinical Intake
                  </h3>
                  <p className="text-xs text-slate-500">
                    Review and confirm or modify each extracted section before finalizing the consultation.
                  </p>
                </div>
                <span className="font-mono text-xs text-teal-800 font-bold bg-teal-50 px-2.5 py-1 rounded-full border border-teal-200">
                  Doctor Verification Mode
                </span>
              </div>

              {/* Section 1: Chief Complaint */}
              <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200/80 space-y-2">
                <div className="flex items-center justify-between">
                  <span className="font-heading font-bold text-xs text-slate-900 uppercase tracking-wider font-mono">
                    1. Chief Complaint (મુખ્ય તકલીફ / मुख्य समस्या)
                  </span>
                  <VerificationButtons
                    status={sectionStatuses['chiefComplaint']}
                    onConfirm={() => handleSectionVerify('chiefComplaint', 'confirmed')}
                    onEdit={() => handleOpenEdit('chiefComplaint', 'Chief Complaint', summaryData.chiefComplaint || patient.chiefComplaint)}
                    onReject={() => handleSectionVerify('chiefComplaint', 'rejected')}
                  />
                </div>
                <p className="text-sm font-semibold text-slate-900">
                  {summaryData.chiefComplaint || patient.chiefComplaint || 'Chest pain for 3 days'}
                </p>
              </div>

              {/* Section 2: History of Present Illness (HPI) */}
              <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200/80 space-y-2">
                <div className="flex items-center justify-between">
                  <span className="font-heading font-bold text-xs text-slate-900 uppercase tracking-wider font-mono">
                    2. History of Present Illness (HPI - SOCRATES Framework)
                  </span>
                  <VerificationButtons
                    status={sectionStatuses['hpi']}
                    onConfirm={() => handleSectionVerify('hpi', 'confirmed')}
                    onEdit={() => handleOpenEdit('hpi', 'History of Present Illness', summaryData.hpi || 'Patient reported dull squeezing substernal pressure radiating to left arm.')}
                    onReject={() => handleSectionVerify('hpi', 'rejected')}
                  />
                </div>
                <p className="text-xs text-slate-800 leading-relaxed">
                  {summaryData.hpi || '48-year-old male with dull squeezing retrosternal chest pain starting 3 days ago on walking upstairs. Pain rated 7/10. Associated with mild diaphoresis and breathlessness. Relieved by resting for 10 minutes.'}
                </p>
              </div>

              {/* Section 3: Past Medical History */}
              <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200/80 space-y-2">
                <div className="flex items-center justify-between">
                  <span className="font-heading font-bold text-xs text-slate-900 uppercase tracking-wider font-mono">
                    3. Past Medical & Surgical History
                  </span>
                  <VerificationButtons
                    status={sectionStatuses['pastMedicalHistory']}
                    onConfirm={() => handleSectionVerify('pastMedicalHistory', 'confirmed')}
                    onEdit={() => handleOpenEdit('pastMedicalHistory', 'Past Medical History', summaryData.pastMedicalHistory || patient.chronicConditions)}
                    onReject={() => handleSectionVerify('pastMedicalHistory', 'rejected')}
                  />
                </div>
                <p className="text-xs text-slate-800 font-medium">
                  {summaryData.pastMedicalHistory || 'Type 2 Diabetes Mellitus diagnosed 4 years ago (Under treatment with Metformin 500mg). No prior myocardial infarction or stent placement.'}
                </p>
              </div>

              {/* Section 4: Current Medications */}
              <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200/80 space-y-2">
                <div className="flex items-center justify-between">
                  <span className="font-heading font-bold text-xs text-slate-900 uppercase tracking-wider font-mono">
                    4. Current Medications (Verified from Intake & OCR)
                  </span>
                  <VerificationButtons
                    status={sectionStatuses['medications']}
                    onConfirm={() => handleSectionVerify('medications', 'confirmed')}
                    onEdit={() => handleOpenEdit('medications', 'Current Medications', summaryData.medications || patient.currentMedications)}
                    onReject={() => handleSectionVerify('medications', 'rejected')}
                  />
                </div>
                <ul className="text-xs text-slate-800 font-medium space-y-1">
                  <li>• Tab Metformin 500 mg — Once daily after breakfast</li>
                  <li>• Tab Telmisartan 40 mg — Once daily morning</li>
                </ul>
              </div>

              {/* Section 5: Allergies & Contradictions */}
              <div className="p-4 rounded-2xl bg-rose-50/70 border border-rose-200 space-y-2">
                <div className="flex items-center justify-between">
                  <span className="font-heading font-bold text-xs text-rose-900 uppercase tracking-wider font-mono flex items-center gap-1.5">
                    <AlertTriangle className="size-3.5 text-rose-600" />
                    5. Known Allergies & Clinical Safety Discrepancies
                  </span>
                  <VerificationButtons
                    status={sectionStatuses['allergies']}
                    onConfirm={() => handleSectionVerify('allergies', 'confirmed')}
                    onEdit={() => handleOpenEdit('allergies', 'Allergies', summaryData.allergies || 'Penicillin hypersensitivity')}
                    onReject={() => handleSectionVerify('allergies', 'rejected')}
                  />
                </div>
                <p className="text-xs text-rose-900 font-semibold">
                  ⚠️ Penicillin / Amoxicillin hypersensitivity documented in historical discharge note (2024). Patient orally reported "No known drug allergies" during kiosk intake. Doctor must verify before prescription.
                </p>
              </div>
            </div>

            {/* Physician Orders & Prescription Pad */}
            <div className="p-5 rounded-3xl bg-white border border-teal-500/40 shadow-md space-y-4">
              <div className="flex items-center justify-between border-b border-slate-100 pb-3">
                <div className="flex items-center gap-2.5">
                  <div className="w-9 h-9 rounded-xl bg-teal-500/20 text-teal-800 flex items-center justify-center">
                    <Stethoscope className="size-5 text-teal-700" />
                  </div>
                  <div>
                    <h3 className="font-heading font-bold text-sm sm:text-base text-slate-900">
                      Physician Orders & Consultation Sign-Off
                    </h3>
                    <p className="text-xs text-slate-500">Dr. Ananya Sharma • DMC-2018-4921</p>
                  </div>
                </div>
                <span className="font-mono text-xs font-bold text-teal-800 bg-teal-50 px-2.5 py-1 rounded-full border border-teal-200">
                  Room 204
                </span>
              </div>

              <div className="space-y-3">
                <div>
                  <label className="block text-xs font-bold text-slate-700 mb-1">
                    Confirmed Working Diagnosis (ICD-10)
                  </label>
                  <input
                    type="text"
                    value={physicianOrders.diagnosis || acceptedICD || 'I20.8 - Other forms of angina pectoris / Exertional Ischemia'}
                    onChange={(e) => setPhysicianOrders(prev => ({ ...prev, diagnosis: e.target.value }))}
                    className="w-full px-3.5 py-2.5 bg-slate-50 border border-slate-300 rounded-xl text-xs font-medium text-slate-900 focus:outline-none focus:border-teal-600 focus:ring-2 focus:ring-teal-100"
                  />
                </div>

                <div>
                  <label className="block text-xs font-bold text-slate-700 mb-1">
                    Physician Clinical Directives & Notes
                  </label>
                  <textarea
                    rows={2}
                    value={physicianOrders.clinicalNotes}
                    onChange={(e) => setPhysicianOrders(prev => ({ ...prev, clinicalNotes: e.target.value }))}
                    placeholder="Enter clinical examination notes, chest auscultation, and follow-up advice..."
                    className="w-full px-3.5 py-2 bg-slate-50 border border-slate-300 rounded-xl text-xs font-medium text-slate-900 focus:outline-none focus:border-teal-600 focus:ring-2 focus:ring-teal-100"
                  />
                </div>

                <div className="p-3 rounded-2xl bg-teal-50/50 border border-teal-200/70 space-y-2">
                  <span className="font-mono text-[10px] font-bold uppercase text-teal-900 block">
                    Active STAT Orders & Prescriptions:
                  </span>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs font-semibold text-slate-800">
                    <span className="p-2 rounded-xl bg-white border border-teal-100">📋 STAT 12-Lead ECG & Serum Troponin-I</span>
                    <span className="p-2 rounded-xl bg-white border border-teal-100">💊 Tab Ecosprin 75mg OD</span>
                    <span className="p-2 rounded-xl bg-white border border-teal-100">💊 Tab Rosuvastatin 20mg QHS</span>
                    <span className="p-2 rounded-xl bg-white border border-teal-100">🥗 Low Sodium Diabetic Diet Advice</span>
                  </div>
                </div>

                <button
                  type="button"
                  onClick={handleSignConsultation}
                  disabled={isCompleted}
                  className={`w-full py-3 px-4 rounded-2xl font-heading font-bold text-xs sm:text-sm shadow-md transition flex items-center justify-center gap-2 cursor-pointer ${
                    isCompleted
                      ? 'bg-emerald-600 text-white cursor-default'
                      : 'bg-gradient-to-r from-teal-700 to-teal-800 hover:from-teal-800 hover:to-teal-900 text-white active:scale-98'
                  }`}
                >
                  <CheckCircle2 className="size-4" />
                  <span>{isCompleted ? 'Consultation Verified & Signed by Dr. Ananya Sharma' : 'Sign & Complete Consultation for Dr. Sharma'}</span>
                </button>
              </div>
            </div>
          </div>
        )}

        {/* TAB 2: PROBLEMS & SYMPTOMS */}
        {activeTab === 'problems' && (
          <div className="space-y-5">
            {/* Primary Problem Card */}
            <div className="p-5 rounded-3xl bg-white border border-slate-200 shadow-xs space-y-3">
              <div className="flex items-center justify-between">
                <span className="font-mono text-xs font-bold text-teal-800 uppercase tracking-wider">
                  Active Clinical Problem
                </span>
                <span className="px-2.5 py-0.5 rounded-full bg-rose-50 text-rose-700 border border-rose-200 text-xs font-bold">
                  High Attention
                </span>
              </div>
              <h3 className="font-heading font-bold text-lg text-slate-900">
                {patient.chiefComplaint || 'Exertional Retrosternal Chest Pain'}
              </h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Patient experiences chest tightness triggered by physical exertion (climbing stairs, brisk walking), lasting 10-15 minutes, relieved by rest.
              </p>
            </div>

            {/* SOCRATES Details Breakdown */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
              <div className="p-3.5 rounded-2xl bg-white border border-slate-200 shadow-2xs space-y-1">
                <span className="font-mono text-[10px] text-slate-400 font-bold uppercase">Site</span>
                <p className="font-heading font-bold text-sm text-slate-900">Retrosternal / Mid-chest</p>
              </div>
              <div className="p-3.5 rounded-2xl bg-white border border-slate-200 shadow-2xs space-y-1">
                <span className="font-mono text-[10px] text-slate-400 font-bold uppercase">Onset</span>
                <p className="font-heading font-bold text-sm text-slate-900">3 days ago (Gradual)</p>
              </div>
              <div className="p-3.5 rounded-2xl bg-white border border-slate-200 shadow-2xs space-y-1">
                <span className="font-mono text-[10px] text-slate-400 font-bold uppercase">Character</span>
                <p className="font-heading font-bold text-sm text-slate-900">Dull squeezing pressure</p>
              </div>
              <div className="p-3.5 rounded-2xl bg-white border border-slate-200 shadow-2xs space-y-1">
                <span className="font-mono text-[10px] text-slate-400 font-bold uppercase">Radiation</span>
                <p className="font-heading font-bold text-sm text-slate-900">Left shoulder & arm</p>
              </div>
              <div className="p-3.5 rounded-2xl bg-white border border-slate-200 shadow-2xs space-y-1">
                <span className="font-mono text-[10px] text-slate-400 font-bold uppercase">Associations</span>
                <p className="font-heading font-bold text-sm text-slate-900">Shortness of breath, sweating</p>
              </div>
              <div className="p-3.5 rounded-2xl bg-white border border-slate-200 shadow-2xs space-y-1">
                <span className="font-mono text-[10px] text-slate-400 font-bold uppercase">Timing</span>
                <p className="font-heading font-bold text-sm text-slate-900">Episodic (With exertion)</p>
              </div>
              <div className="p-3.5 rounded-2xl bg-white border border-slate-200 shadow-2xs space-y-1">
                <span className="font-mono text-[10px] text-slate-400 font-bold uppercase">Relieving Factors</span>
                <p className="font-heading font-bold text-sm text-slate-900">Rest, cessation of movement</p>
              </div>
              <div className="p-3.5 rounded-2xl bg-white border border-slate-200 shadow-2xs space-y-1">
                <span className="font-mono text-[10px] text-slate-400 font-bold uppercase">Severity Rating</span>
                <p className="font-heading font-bold text-sm text-teal-800">7 out of 10</p>
              </div>
            </div>

            {/* Clinical Signals */}
            <div className="p-4 rounded-3xl bg-white border border-slate-200 shadow-xs space-y-3">
              <h4 className="font-heading font-bold text-sm text-slate-900">
                Identified Clinical Signals & Red Flags
              </h4>
              <div className="space-y-2">
                <div className="p-3 rounded-2xl bg-rose-50 border border-rose-200 text-xs text-rose-900 font-medium flex items-start gap-2">
                  <AlertTriangle className="size-4 text-rose-600 shrink-0 mt-0.5" />
                  <div>
                    <span className="font-bold">Anginal Equivalence Alert:</span> Retrosternal squeezing radiating to left arm in a diabetic patient warrants acute coronary syndrome rule-out.
                  </div>
                </div>

                <div className="p-3 rounded-2xl bg-amber-50 border border-amber-200 text-xs text-amber-900 font-medium flex items-start gap-2">
                  <AlertTriangle className="size-4 text-amber-600 shrink-0 mt-0.5" />
                  <div>
                    <span className="font-bold">Glycemic Control Risk:</span> Elevated HbA1c (7.8%) from previous lab records increases cardiovascular event risk.
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* TAB 3: MEDICAL REPORTS & OCR INVESTIGATIONS */}
        {activeTab === 'documents' && (
          <div className="space-y-5">
            <div className="p-4 rounded-3xl bg-white border border-slate-200 shadow-xs flex items-center justify-between">
              <div>
                <h3 className="font-heading font-bold text-sm text-slate-900">
                  Uploaded Medical Records ({documents.length > 0 ? documents.length : 2})
                </h3>
                <p className="text-xs text-slate-500">
                  Scanned via hospital kiosk client-side OCR & document intelligence engine.
                </p>
              </div>
            </div>

            {/* Records Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {/* Document 1: Prescription */}
              <div className="p-4 rounded-3xl bg-white border border-slate-200 shadow-xs space-y-3">
                <div className="flex items-center justify-between">
                  <span className="px-2.5 py-1 rounded-xl bg-teal-50 text-teal-800 text-xs font-bold border border-teal-200 font-mono">
                    Prescription Scan
                  </span>
                  <span className="text-[11px] text-slate-400 font-mono">12 May 2025</span>
                </div>
                <p className="font-heading font-bold text-sm text-slate-900">
                  Cardiology Clinic OPD Prescription (Dr. Alok Verma)
                </p>
                <div className="p-3 rounded-2xl bg-slate-50 text-xs text-slate-700 space-y-1 font-mono">
                  <p>• Tab Metformin 500mg - 1-0-0</p>
                  <p>• Tab Telmisartan 40mg - 1-0-0</p>
                  <p>• Advised low sodium diet</p>
                </div>
                <button
                  type="button"
                  onClick={() => setActiveInspectorDoc({
                    title: 'Cardiology Clinic OPD Prescription',
                    category: 'Prescription',
                    confidence: 0.96,
                    extractedData: {
                      medications: [
                        { name: 'Metformin', strength: '500 mg', frequency: 'OD' },
                        { name: 'Telmisartan', strength: '40 mg', frequency: 'OD' }
                      ]
                    }
                  })}
                  className="w-full py-2 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-800 font-bold text-xs transition cursor-pointer flex items-center justify-center gap-1.5"
                >
                  <Eye className="size-3.5" />
                  <span>Inspect OCR Extraction</span>
                </button>
              </div>

              {/* Document 2: Lab Report */}
              <div className="p-4 rounded-3xl bg-white border border-slate-200 shadow-xs space-y-3">
                <div className="flex items-center justify-between">
                  <span className="px-2.5 py-1 rounded-xl bg-cyan-50 text-cyan-800 text-xs font-bold border border-cyan-200 font-mono">
                    Diagnostic Lab Report
                  </span>
                  <span className="text-[11px] text-slate-400 font-mono">18 Jan 2025</span>
                </div>
                <p className="font-heading font-bold text-sm text-slate-900">
                  Metabolic & Glycemic Profile (Thyrocare Laboratories)
                </p>
                <div className="p-3 rounded-2xl bg-slate-50 text-xs text-slate-700 space-y-1 font-mono">
                  <p>• HbA1c: 7.8% (Target &lt;6.5%) — <span className="text-amber-700 font-bold">Elevated</span></p>
                  <p>• Fasting Blood Sugar: 142 mg/dL — <span className="text-amber-700 font-bold">High</span></p>
                  <p>• Serum Creatinine: 1.0 mg/dL — Normal</p>
                </div>
                <button
                  type="button"
                  onClick={() => setActiveInspectorDoc({
                    title: 'Metabolic & Glycemic Profile',
                    category: 'Lab Report',
                    confidence: 0.98,
                    extractedData: {
                      investigations: [
                        { test: 'HbA1c', value: '7.8', unit: '%', status: 'abnormal' },
                        { test: 'Fasting Blood Sugar', value: '142', unit: 'mg/dL', status: 'abnormal' }
                      ]
                    }
                  })}
                  className="w-full py-2 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-800 font-bold text-xs transition cursor-pointer flex items-center justify-center gap-1.5"
                >
                  <Eye className="size-3.5" />
                  <span>Inspect Lab Values</span>
                </button>
              </div>
            </div>
          </div>
        )}

        {/* TAB 4: CHRONOLOGICAL TIMELINE */}
        {activeTab === 'timeline' && (
          <div className="p-5 rounded-3xl bg-white border border-slate-200 shadow-xs space-y-4">
            <h3 className="font-heading font-bold text-base text-slate-900">
              Integrated Patient Health Journey
            </h3>
            <Timeline events={timeline.length > 0 ? timeline : [
              { date: 'Today, 11:15 AM', title: 'Hospital Intake Kiosk Check-In', description: 'Rahul Sharma completed automated clinical intake interview & voice triage.', category: 'consultation' },
              { date: '12 May 2025', title: 'Cardiology OPD Consultation', description: 'Consultation with Dr. Alok Verma for mild chest heaviness. Prescribed Metformin & Telmisartan.', category: 'prescription' },
              { date: '18 Jan 2025', title: 'Diagnostic Lab Investigations', description: 'HbA1c recorded at 7.8%, Fasting Blood Glucose 142 mg/dL.', category: 'lab' },
              { date: '14 Nov 2024', title: 'Inpatient Hospitalization & Penicillin Allergy', description: 'Admitted for acute bronchitis. Developed cutaneous rash following amoxicillin.', category: 'allergy' },
            ]} />
          </div>
        )}

        {/* TAB 5: AYUSH DASHAVIDHA PARIKSHA */}
        {activeTab === 'ayush' && (
          <div className="p-5 rounded-3xl bg-white border border-slate-200 shadow-xs space-y-4">
            <div className="flex items-center justify-between border-b border-slate-100 pb-3">
              <div className="flex items-center gap-2">
                <span className="text-2xl">🌿</span>
                <div>
                  <h3 className="font-heading font-bold text-base text-slate-900">
                    Dashavidha & Ashtavidha Pariksha (AYUSH Protocol)
                  </h3>
                  <p className="text-xs text-slate-500">
                    Ayurvedic clinical assessment framework documented during patient intake.
                  </p>
                </div>
              </div>
              <span className="font-mono text-xs font-bold text-emerald-800 bg-emerald-50 px-3 py-1 rounded-full border border-emerald-200">
                Pitta-Kapha Prakriti
              </span>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 text-xs">
              <div className="p-3 rounded-2xl bg-slate-50 border border-slate-200/80">
                <span className="font-mono text-[10px] text-slate-400 font-bold uppercase">Prakriti (Constitution)</span>
                <p className="font-heading font-bold text-slate-900 mt-0.5">Pitta-Kapha dominant</p>
              </div>
              <div className="p-3 rounded-2xl bg-slate-50 border border-slate-200/80">
                <span className="font-mono text-[10px] text-slate-400 font-bold uppercase">Agni (Digestive Fire)</span>
                <p className="font-heading font-bold text-slate-900 mt-0.5">Mandagni (Sluggish metabolism)</p>
              </div>
              <div className="p-3 rounded-2xl bg-slate-50 border border-slate-200/80">
                <span className="font-mono text-[10px] text-slate-400 font-bold uppercase">Kostha (Bowel Pattern)</span>
                <p className="font-heading font-bold text-slate-900 mt-0.5">Madhyama Kostha</p>
              </div>
              <div className="p-3 rounded-2xl bg-slate-50 border border-slate-200/80">
                <span className="font-mono text-[10px] text-slate-400 font-bold uppercase">Dhatu Sarata</span>
                <p className="font-heading font-bold text-slate-900 mt-0.5">Meda & Rakta Dhatu vitiation</p>
              </div>
              <div className="p-3 rounded-2xl bg-slate-50 border border-slate-200/80">
                <span className="font-mono text-[10px] text-slate-400 font-bold uppercase">Nadi (Pulse)</span>
                <p className="font-heading font-bold text-slate-900 mt-0.5">Manduka-Sarpa Gati (76 bpm, regular)</p>
              </div>
              <div className="p-3 rounded-2xl bg-slate-50 border border-slate-200/80">
                <span className="font-mono text-[10px] text-slate-400 font-bold uppercase">Complementary AYUSH Dravya</span>
                <p className="font-heading font-bold text-slate-900 mt-0.5">Arjuna Ksheerapaka & Methi Churna</p>
              </div>
            </div>
          </div>
        )}
      </main>

      {/* Document Inspector Modal */}
      <DocumentInspectorModal
        isOpen={Boolean(activeInspectorDoc)}
        onClose={() => setActiveInspectorDoc(null)}
        documentData={activeInspectorDoc}
      />

      {/* FHIR Bundle Export Modal */}
      {fhirModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/70 backdrop-blur-sm select-none">
          <div className="bg-white rounded-3xl p-6 max-w-lg w-full space-y-4 border border-slate-200 shadow-2xl">
            <div className="flex items-center justify-between pb-2 border-b border-slate-100">
              <span className="font-heading font-bold text-sm text-slate-900">
                HL7 FHIR R4 Bundle Generator (ABDM Compliant)
              </span>
              <button
                type="button"
                onClick={() => setFhirModalOpen(false)}
                className="w-7 h-7 rounded-full bg-slate-100 hover:bg-slate-200 text-slate-500 flex items-center justify-center text-xs cursor-pointer"
              >
                ✕
              </button>
            </div>

            <p className="text-xs text-slate-600 leading-relaxed">
              Standardized HL7 FHIR Document Bundle prepared for push to hospital EHR / ABDM repository:
            </p>

            <pre className="p-3 bg-slate-900 text-teal-300 rounded-2xl font-mono text-[10px] max-h-60 overflow-y-auto leading-tight">
              {JSON.stringify(prepareFHIRBundle(patient), null, 2)}
            </pre>

            <div className="flex gap-2">
              <button
                type="button"
                onClick={() => setFhirModalOpen(false)}
                className="flex-1 py-2 rounded-xl border border-slate-200 text-xs font-bold text-slate-700 cursor-pointer"
              >
                Close
              </button>
              <button
                type="button"
                onClick={() => {
                  navigator.clipboard?.writeText(JSON.stringify(prepareFHIRBundle(patient), null, 2))
                  alert('FHIR R4 JSON copied to clipboard!')
                }}
                className="flex-1 py-2 rounded-xl bg-teal-700 text-white text-xs font-bold cursor-pointer"
              >
                Copy FHIR JSON
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Edit Section Modal */}
      {editModal.isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/70 backdrop-blur-sm select-none">
          <div className="bg-white rounded-3xl p-6 max-w-md w-full space-y-4 border border-slate-200 shadow-2xl">
            <div className="flex items-center justify-between pb-2 border-b border-slate-100">
              <span className="font-heading font-bold text-sm text-slate-900">
                Edit {editModal.title}
              </span>
              <button
                type="button"
                onClick={() => setEditModal({ isOpen: false, sectionKey: '', title: '', textValue: '' })}
                className="w-7 h-7 rounded-full bg-slate-100 text-slate-500 flex items-center justify-center text-xs"
              >
                ✕
              </button>
            </div>

            <textarea
              rows={4}
              value={editModal.textValue}
              onChange={(e) => setEditModal(prev => ({ ...prev, textValue: e.target.value }))}
              className="w-full p-3 bg-slate-50 border border-slate-300 rounded-xl text-xs text-slate-900 focus:outline-none focus:border-teal-600 font-medium"
            />

            <div className="flex gap-2">
              <button
                type="button"
                onClick={() => setEditModal({ isOpen: false, sectionKey: '', title: '', textValue: '' })}
                className="flex-1 py-2 rounded-xl border border-slate-200 text-xs font-bold text-slate-700"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={handleSaveEdit}
                className="flex-1 py-2 rounded-xl bg-teal-700 text-white text-xs font-bold"
              >
                Save Correction
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
